"""Tool to generate a markdown table of Python files, functions, and descriptions.

This tool scans the repository for Python files, extracts top‑level
functions (including their docstrings), and writes a Markdown table
to ``repo_overview.md`` in the repository root.
"""

import ast
import os
from pathlib import Path

# ---------------------------------------------------------------------------
# Helper: walk Python files in the repo
# ---------------------------------------------------------------------------

def walk_python_files(root: Path) -> list[Path]:
    return sorted(p for p in root.rglob("*.py") if p.is_file())

# ---------------------------------------------------------------------------
# Extract function info from a module file
# ---------------------------------------------------------------------------

def extract_functions_from_file(path: Path) -> list[tuple[str, str]]:
    """Return a list of (function_name, docstring) for top‑level functions.

    Functions defined inside classes or other functions are ignored.
    """
    with path.open("r", encoding="utf-8") as f:
        source = f.read()
    tree = ast.parse(source, filename=str(path))
    funcs: list[tuple[str, str]] = []
    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            name = node.name
            doc = ast.get_docstring(node) or ""
            funcs.append((name, doc.strip()))
    return funcs

# ---------------------------------------------------------------------------
# Build markdown table
# ---------------------------------------------------------------------------

def build_markdown_table(file_funcs: dict[Path, list[tuple[str, str]]]) -> str:
    lines = [
        "| Relative path | Function | Description |",
        "|---------------|----------|-------------|",
    ]
    for path, funcs in sorted(file_funcs.items()):
        rel = str(path.relative_to(Path.cwd()))
        for name, doc in funcs:
            doc = doc.replace("\n", " ")  # one‑line
            lines.append(f"| {rel} | {name} | {doc} |")
    return "\n".join(lines)

# ---------------------------------------------------------------------------
# The tool entry point
# ---------------------------------------------------------------------------

def func() -> str:
    """Generate a markdown table of all Python functions in the repo.

    The table is written to ``repo_overview.md`` in the repository root.
    """
    repo_root = Path.cwd()  # the tool is run from repo root
    py_files = walk_python_files(repo_root)
    file_funcs: dict[Path, list[tuple[str, str]]] = {}
    for p in py_files:
        funcs = extract_functions_from_file(p)
        if funcs:
            file_funcs[p] = funcs
    md = build_markdown_table(file_funcs)
    return md
    out_path = repo_root / "repo_overview.md"
    # out_path.write_text(md, encoding="utf-8")
    # return f"Markdown table written to {out_path.name}"

# ---------------------------------------------------------------------------
# Tool metadata
# ---------------------------------------------------------------------------
name = "repo_overview"
description = "Generate a markdown table of all Python functions in the repo and save it to repo_overview.md"
# schema will be auto‑generated by app/tools/__init__.py

# ---------------------------------------------------------------------------
# If run directly, execute the function
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print(func())
